---

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: docker_test
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./FoundryData
        target: /data
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
